<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SectionContentSeeder extends Seeder
{
    public function run()
    {
        DB::table('section_contents')->truncate();
        
        DB::table('section_contents')->insert([
            [
                'id' => 1,
                'section_id' => 1,
                'content_key' => 'Kualitas Terjamin',
                'content_value' => 'Produk unggulan untuk performa maksimal.',
                'type' => 'text',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 2,
                'section_id' => 1,
                'content_key' => ' Pemasangan Mudah',
                'content_value' => 'Dirancang untuk presisi tanpa ribet.',
                'type' => 'text',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 3,
                'section_id' => 1,
                'content_key' => 'Didesain untuk performa',
                'content_value' => 'Cocok untuk motor harian hingga modifikasi.',
                'type' => 'text',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 4,
                'section_id' => 2,
                'content_key' => 'email',
                'content_value' => 'info@example.com',
                'type' => 'text',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 5,
                'section_id' => 2,
                'content_key' => 'address',
                'content_value' => '123 Street Name, City, Country',
                'type' => 'text',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 6,
                'section_id' => 2,
                'content_key' => 'postal_address',
                'content_value' => 'Cimahi, Bandung',
                'type' => 'text',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-21 16:22:53',
                'updated_at' => '2025-03-21 16:22:53',
            ],
            [
                'id' => 7,
                'section_id' => 2,
                'content_key' => 'phone',
                'content_value' => '08211990442',
                'type' => 'text',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-21 16:22:53',
                'updated_at' => '2025-03-21 16:22:53',
            ],
            [
                'id' => 8,
                'section_id' => 2,
                'content_key' => 'work_time_weekdays',
                'content_value' => 'Senin - Jumat : 08:00 - 17:00',
                'type' => 'text',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-21 16:22:53',
                'updated_at' => '2025-03-21 16:22:53',
            ],
            [
                'id' => 9,
                'section_id' => 2,
                'content_key' => 'work_time_weekend',
                'content_value' => 'Sabtu - Minggu : 10:00 - 16:00',
                'type' => 'text',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-21 16:22:53',
                'updated_at' => '2025-03-21 16:22:53',
            ],
            [
                'id' => 10,
                'section_id' => 3,
                'content_key' => 'Working Hours',
                'content_value' => '5600',
                'type' => 'number',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 11,
                'section_id' => 3,
                'content_key' => 'Happy Clients',
                'content_value' => '220',
                'type' => 'number',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 12,
                'section_id' => 3,
                'content_key' => 'Awards',
                'content_value' => '108',
                'type' => 'number',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 13,
                'section_id' => 3,
                'content_key' => 'Projects a Year',
                'content_value' => '650',
                'type' => 'number',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            // Adding more records... (continuing with the pattern from your SQL data)
            [
                'id' => 53,
                'section_id' => 13,
                'content_key' => 'Upgrade Your Ride Today!',
                'content_value' => 'Get the best spare parts and professional installation for your motorbike.',
                'type' => 'text',
                'extra_data' => null,
                'show_order' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 54,
                'section_id' => 14,
                'content_key' => 'LAMPU',
                'content_value' => '',
                'type' => 'image',
                'extra_data' => '{"image": "landing/images/categories/categories-1.png", "link": "https://shopee.co.id/boyprojectsasli?originalCategoryId=11043768#product_list"}',
                'show_order' => 1,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 55,
                'section_id' => 14,
                'content_key' => 'MOUNTING',
                'content_value' => '',
                'type' => 'image',
                'extra_data' => '{"image": "landing/images/categories/categories-2.png", "link": "https://shopee.co.id/boyprojectsasli?originalCategoryId=11043764#product_list"}',
                'show_order' => 1,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 56,
                'section_id' => 14,
                'content_key' => 'SERVICE',
                'content_value' => '',
                'type' => 'image',
                'extra_data' => '{"image": "landing/images/categories/default.png", "link": ""}',
                'show_order' => 1,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
            [
                'id' => 57,
                'section_id' => 14,
                'content_key' => 'SOMETHING',
                'content_value' => '',
                'type' => 'image',
                'extra_data' => '{"image": "landing/images/categories/default.png", "link": ""}',
                'show_order' => 1,
                'created_at' => '2025-03-20 04:22:22',
                'updated_at' => '2025-03-20 04:22:22',
            ],
        ]);
    }
}
