<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SectionSeeder extends Seeder
{
    public function run()
    {
        DB::table('sections')->truncate();
        
        DB::table('sections')->insert([
            [
                'id' => 1,
                'name' => 'about',
                'title' => 'Redefining Performance',
                'description' => 'Lebih dari Sekadar Sparepart, Ini Tentang Pengalaman Berkendara',
                'content' => 'Di Boy Project, kami menghadirkan produk terbaik untuk meningkatkan performa dan estetika motor Anda. Setiap sparepart yang kami sediakan dipilih dengan cermat untuk memberikan kualitas, ketahanan, dan kenyamanan terbaik bagi para rider.',
                'image' => 'landing/images/startup-bg.jpg',
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 2,
                'created_at' => '2025-03-20 11:21:56',
                'updated_at' => '2025-06-03 06:08:33',
            ],
            [
                'id' => 2,
                'name' => 'contact',
                'title' => 'Contact Us',
                'description' => '- Stay in Touch -',
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 8,
                'created_at' => '2025-03-20 11:21:56',
                'updated_at' => '2025-03-20 11:21:56',
            ],
            [
                'id' => 3,
                'name' => 'counter',
                'title' => 'Our Achievements',
                'description' => 'We have achieved great milestones over the years.',
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 6,
                'created_at' => '2025-03-20 11:21:56',
                'updated_at' => '2025-03-20 11:21:56',
            ],
            [
                'id' => 4,
                'name' => 'portofolio',
                'title' => 'Our Work',
                'description' => 'Explore our best projects in various categories.',
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 7,
                'created_at' => '2025-03-20 11:21:56',
                'updated_at' => '2025-03-20 11:21:56',
            ],
            [
                'id' => 5,
                'name' => 'pricing',
                'title' => 'Our Pricing',
                'description' => '- Choose Your Plan -',
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 10,
                'created_at' => '2025-03-20 11:23:12',
                'updated_at' => '2025-03-20 11:23:12',
            ],
            [
                'id' => 6,
                'name' => 'services',
                'title' => 'Apa yang Kami Tawarkan',
                'description' => '- Enhancing Your Performance -',
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 4,
                'created_at' => '2025-03-20 11:24:18',
                'updated_at' => '2025-03-20 11:24:18',
            ],
            [
                'id' => 7,
                'name' => 'promotion',
                'title' => 'NEW PRODUCTS',
                'description' => 'get promotion info',
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 2,
                'show_order' => 5,
                'created_at' => '2025-03-20 11:25:06',
                'updated_at' => '2025-03-20 11:25:06',
            ],
            [
                'id' => 8,
                'name' => 'testimonials',
                'title' => 'Testimonials',
                'description' => '- Happy Clients -',
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 9,
                'created_at' => '2025-03-20 11:25:39',
                'updated_at' => '2025-03-20 11:25:39',
            ],
            [
                'id' => 9,
                'name' => 'home',
                'title' => 'Welcome to Boys Project',
                'description' => 'Jual beli sparepart motor & pemasangan terpercaya',
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 1,
                'created_at' => '2025-03-20 11:37:27',
                'updated_at' => '2025-06-03 06:15:56',
            ],
            [
                'id' => 10,
                'name' => 'tiktok',
                'title' => 'Our TikTok Content',
                'description' => 'Latest updates from TikTok',
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 12,
                'created_at' => '2025-03-20 12:02:27',
                'updated_at' => '2025-03-20 12:02:27',
            ],
            [
                'id' => 11,
                'name' => 'instagram',
                'title' => 'Our Instagram Posts',
                'description' => 'Latest updates from Instagram',
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 13,
                'created_at' => '2025-03-20 12:03:17',
                'updated_at' => '2025-03-20 12:03:17',
            ],
            [
                'id' => 12,
                'name' => 'activities',
                'title' => 'Our Activities',
                'description' => 'Lebih dari Sekadar Produk, Ini Tentang Perjalanan Bersama',
                'content' => null,
                'image' => 'landing/images/onepage-bg-left.jpg',
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 3,
                'created_at' => '2025-03-21 04:40:43',
                'updated_at' => '2025-03-21 04:40:43',
            ],
            [
                'id' => 13,
                'name' => 'cta',
                'title' => 'Take Action Now!',
                'description' => 'Join us and upgrade your bike today!',
                'content' => 'Get the best spare parts and professional installation for your motorbike.',
                'image' => 'landing/images/background/parallax-bg-2.jpg',
                'button_text' => 'Chat Us!!',
                'button_link' => 'https://wa.me/08211990442',
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 11,
                'created_at' => '2025-03-21 04:52:50',
                'updated_at' => '2025-03-21 04:52:50',
            ],
            [
                'id' => 14,
                'name' => 'categories',
                'title' => 'WHAT WE OFFER',
                'description' => null,
                'content' => null,
                'image' => null,
                'button_text' => null,
                'button_link' => null,
                'is_active' => 1,
                'layout' => 1,
                'show_order' => 3,
                'created_at' => '2025-04-20 23:47:43',
                'updated_at' => '2025-04-20 23:47:43',
            ],
        ]);
    }
}
